# Seiteneinstellungen
title: Jasmin Portfolio
description: "Jasmin von Reth" # Maximal 160 Zeichen
author: jvonreth
email: jasmin.vonreth@gmail.com
url: "http://localhost:3000" # Basis-Hostname f端r Development
# url: "" # Basis-Hostname f端r Production
baseurl: "" # Pfad in welchem die Jekyll-Seite gehostet wird
locale: "de"
encoding: "utf-8"

# Einstellungen f端r den Build-Prozess
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
highlighter: rouge
lsi: false

# Dateien die im Build-Prozess nicht ber端cksichtigt werden sollen
exclude:
  - README.md
  - LICENSE.md
  - package.json
  - gulpfile.js
  - node_modules
  - "*.sublime-project"
  - "*.sublime-workspace"

# Navigation
navigation:
  - title: home
    url: /index.html
